import { StyleSheet } from 'react-native';
import { colors, fonts, TAB_BAR_RESERVE, uiFont } from '../theme';

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  body: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 24,
  },
  tabSceneContent: {
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: TAB_BAR_RESERVE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  chevron: {
    fontSize: 28,
    lineHeight: 32,
    color: colors.text,
    marginTop: -2,
  },
  brand: {
    fontFamily: fonts.regular,
    fontSize: 17,
    color: colors.text,
  },
  title: {
    marginTop: 10,
    marginBottom: 12,
    fontFamily: fonts.bold,
    fontSize: 34,
    color: colors.text,
  },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 22,
    height: 44,
    paddingHorizontal: 14,
    gap: 8,
    marginBottom: 22,
  },
  searchInput: {
    flex: 1,
    fontFamily: uiFont,
    fontSize: 17,
    color: colors.text,
    paddingVertical: 0,
  },
  sectionTitle: {
    fontFamily: fonts.bold,
    fontSize: 22,
    color: colors.text,
    marginBottom: 12,
  },
  categories: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 22,
    gap: 8,
  },
  categoryCol: {
    flex: 1,
    alignItems: 'center',
  },
  category: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 16,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryImage: {
    ...StyleSheet.absoluteFill,
  },
  categoryScrim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.32)',
  },
  categoryLabel: {
    fontFamily: uiFont,
    fontSize: 13,
    color: colors.text,
    marginTop: 6,
    textAlign: 'center',
    width: '100%',
  },
  followRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
    width: '100%',
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    overflow: 'hidden',
  },
  photoFill: {
    width: '100%',
    height: '100%',
  },
  followName: {
    fontFamily: fonts.semibold,
    fontSize: 15,
    color: colors.text,
  },
  followMeta: {
    fontFamily: uiFont,
    fontSize: 13,
    color: colors.muted,
    marginTop: 1,
  },
  products: {
    flexDirection: 'row',
    gap: 12,
  },
  product: {
    borderRadius: 20,
    overflow: 'hidden',
    width: '100%',
    backgroundColor: colors.white,
  },
  productArt: {
    width: '100%',
    height: 120,
  },
  productInfo: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  productName: {
    fontFamily: fonts.semibold,
    fontSize: 14,
    color: colors.text,
  },
  productPrice: {
    fontFamily: fonts.regular,
    fontSize: 13,
    marginTop: 2,
  },
  tabBarDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
  },
  tabBarShell: {
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.tabBarBorder,
  },
  tabBarBlur: {
    ...StyleSheet.absoluteFill,
  },
  tabBarFill: {
    ...StyleSheet.absoluteFill,
  },
  tabBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 6,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  tabItemInner: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    maxWidth: '100%',
  },
  tabLabel: {
    fontFamily: uiFont,
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 0.1,
    color: colors.tabInactive,
    textAlign: 'center',
  },
  tabLabelActive: {
    color: colors.text,
    fontWeight: '600',
  },
  placeholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  placeholderTitle: {
    fontFamily: fonts.bold,
    fontSize: 28,
    color: colors.text,
    marginBottom: 8,
  },
  empty: {
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.muted,
    marginBottom: 16,
  },
  categorySelected: {
    borderWidth: 3,
    borderColor: colors.text,
  },
  heartWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  badge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  badgeText: {
    fontFamily: uiFont,
    fontSize: 11,
    fontWeight: '700',
    color: colors.white,
  },
  detailArt: {
    width: '100%',
    height: 200,
    borderRadius: 24,
    marginTop: 8,
    marginBottom: 18,
    overflow: 'hidden',
  },
  detailPrice: {
    fontFamily: fonts.bold,
    fontSize: 28,
    color: colors.text,
    marginBottom: 8,
  },
  detailBlurb: {
    fontFamily: fonts.regular,
    fontSize: 15,
    color: colors.muted,
    lineHeight: 22,
    marginBottom: 22,
  },
  primaryBtn: {
    backgroundColor: colors.text,
    borderRadius: 28,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  primaryBtnText: {
    fontFamily: fonts.bold,
    fontSize: 17,
    color: colors.white,
  },
  ghostBtn: {
    borderRadius: 28,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.text,
  },
  ghostBtnText: {
    fontFamily: fonts.regular,
    fontSize: 16,
    color: colors.text,
  },
  post: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
  },
  postTime: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: colors.muted,
    marginTop: 8,
  },
  profileCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    padding: 18,
    marginBottom: 18,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  profileIdentity: {
    flex: 1,
  },
  profileAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.starship,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  stats: {
    flexDirection: 'row',
    marginBottom: 18,
    gap: 10,
  },
  statCol: {
    flex: 1,
  },
  stat: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
  },
  statValue: {
    fontFamily: fonts.bold,
    fontSize: 18,
    color: colors.text,
  },
  statLabel: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
  wrap: {
    flexWrap: 'wrap',
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  productTile: {
    width: '48%',
    marginBottom: 4,
  },
  greeting: {
    fontFamily: fonts.regular,
    fontSize: 17,
    color: colors.muted,
    marginTop: 4,
  },
  emptyCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
  },
  emptyTitle: {
    fontFamily: fonts.semibold,
    fontSize: 16,
    color: colors.text,
    marginBottom: 6,
  },
  toast: {
    position: 'absolute',
    top: 12,
    left: 18,
    right: 18,
    backgroundColor: colors.text,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    zIndex: 40,
  },
  toastText: {
    fontFamily: fonts.medium,
    fontSize: 15,
    color: colors.white,
    textAlign: 'center',
  },
  chips: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  chip: {
    paddingHorizontal: 14,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipActive: {
    backgroundColor: colors.text,
  },
  chipText: {
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.text,
  },
  chipTextActive: {
    color: colors.white,
  },
  composer: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 12,
    marginBottom: 16,
  },
  composerInput: {
    fontFamily: fonts.regular,
    fontSize: 15,
    color: colors.text,
    minHeight: 44,
    textAlignVertical: 'top',
  },
  likeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
  },
  likeText: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: colors.muted,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 10,
  },
  orderRow: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(17,17,17,0.45)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 28,
  },
  nameInput: {
    fontFamily: fonts.semibold,
    fontSize: 17,
    color: colors.text,
    paddingVertical: 0,
    width: '100%',
  },
  fieldError: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: '#C0392B',
    marginTop: 6,
    marginBottom: 8,
  },
  composerError: {
    borderWidth: 1.5,
    borderColor: '#C0392B',
  },
  heartBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBadge: {
    position: 'absolute',
    top: 4,
    right: 2,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.starship,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  dropRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
  },
  dropRowUnread: {
    borderWidth: 1.5,
    borderColor: colors.text,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.starship,
  },
  memberHint: {
    fontFamily: fonts.semibold,
    fontSize: 15,
    color: colors.jungle,
    marginBottom: 14,
  },
  includeBadge: {
    fontFamily: uiFont,
    fontSize: 13,
    color: colors.jungle,
    marginTop: 4,
  },
  tierRow: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  tierRowActive: {
    borderColor: colors.text,
  },
  lockedText: {
    fontFamily: fonts.regular,
    fontSize: 15,
    color: colors.muted,
    lineHeight: 22,
    marginBottom: 10,
  },
  libraryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 10,
    marginBottom: 10,
    gap: 12,
  },
  libraryThumb: {
    width: 56,
    height: 56,
    borderRadius: 12,
  },
  libraryMeta: {
    flex: 1,
  },
  fileRow: {
    backgroundColor: colors.white,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  mediaStage: {
    width: '100%',
    height: 220,
    borderRadius: 20,
    backgroundColor: '#111111',
    overflow: 'hidden',
  },
  docPage: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 12,
    marginBottom: 12,
  },
  docPageLabel: {
    fontFamily: uiFont,
    fontSize: 13,
    color: colors.muted,
    marginBottom: 8,
  },
  docPageImage: {
    width: '100%',
    height: 280,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
});
