import { StyleSheet } from 'react-native';
import { colors, fonts } from '../theme';

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  body: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 24,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  chevron: {
    fontSize: 28,
    lineHeight: 32,
    color: colors.text,
    marginTop: -2,
  },
  brand: {
    fontFamily: fonts.regular,
    fontSize: 17,
    color: colors.text,
  },
  title: {
    marginTop: 10,
    marginBottom: 12,
    fontFamily: fonts.bold,
    fontSize: 34,
    color: colors.text,
  },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 22,
    height: 44,
    paddingHorizontal: 14,
    gap: 8,
    marginBottom: 22,
  },
  searchInput: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.text,
    paddingVertical: 0,
  },
  sectionTitle: {
    fontFamily: fonts.bold,
    fontSize: 22,
    color: colors.text,
    marginBottom: 12,
  },
  categories: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 22,
  },
  category: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  categoryLabel: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: colors.white,
  },
  followRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  followName: {
    fontFamily: fonts.semibold,
    fontSize: 15,
    color: colors.text,
  },
  followMeta: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: colors.muted,
    marginTop: 1,
  },
  products: {
    flexDirection: 'row',
    gap: 12,
  },
  product: {
    flex: 1,
    borderRadius: 20,
    overflow: 'hidden',
  },
  productArt: {
    height: 92,
  },
  productInfo: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  productName: {
    fontFamily: fonts.semibold,
    fontSize: 14,
    color: colors.text,
  },
  productPrice: {
    fontFamily: fonts.regular,
    fontSize: 13,
    marginTop: 2,
  },
  tabBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 8,
    paddingHorizontal: 8,
    backgroundColor: colors.background,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#D8DDD8',
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 64,
    gap: 4,
  },
  tabActiveIcon: {
    width: 42,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabLabel: {
    fontFamily: fonts.regular,
    fontSize: 11,
    color: colors.tabInactive,
  },
  tabLabelActive: {
    color: colors.text,
  },
  placeholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  placeholderTitle: {
    fontFamily: fonts.bold,
    fontSize: 28,
    color: colors.text,
    marginBottom: 8,
  },
  empty: {
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.muted,
    marginBottom: 16,
  },
  categorySelected: {
    borderWidth: 3,
    borderColor: colors.text,
  },
  heartWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  badge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  badgeText: {
    fontFamily: fonts.bold,
    fontSize: 10,
    color: colors.white,
  },
  detailArt: {
    height: 180,
    borderRadius: 24,
    marginTop: 8,
    marginBottom: 18,
  },
  detailPrice: {
    fontFamily: fonts.bold,
    fontSize: 28,
    color: colors.text,
    marginBottom: 8,
  },
  detailBlurb: {
    fontFamily: fonts.regular,
    fontSize: 15,
    color: colors.muted,
    lineHeight: 22,
    marginBottom: 22,
  },
  primaryBtn: {
    backgroundColor: colors.text,
    borderRadius: 28,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  primaryBtnText: {
    fontFamily: fonts.bold,
    fontSize: 17,
    color: colors.white,
  },
  ghostBtn: {
    borderRadius: 28,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.text,
  },
  ghostBtnText: {
    fontFamily: fonts.regular,
    fontSize: 16,
    color: colors.text,
  },
  post: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
  },
  postTime: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: colors.muted,
    marginTop: 8,
  },
  profileCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    padding: 18,
    marginBottom: 18,
  },
  profileAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.starship,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  stats: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  stat: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
  statValue: {
    fontFamily: fonts.bold,
    fontSize: 18,
    color: colors.text,
  },
  statLabel: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
  wrap: {
    flexWrap: 'wrap',
  },
});
